related_words = {
    (_('ICE CREAM FLAVORS')): ['berry', 'cream', 'ice', 'vanilla', 'choco', 'sweet', 'cold', 'treat', 'scoop', 'cone'],
    (_('FRUITS')): ['fruit', 'apple', 'banana', 'peach', 'grape', 'citrus', 'plum', 'melon', 'mango', 'kiwi'],
    (_('VEGETABLES')): ['greens', 'carrot', 'beans', 'pea', 'beet', 'onion', 'cabbage', 'squash', 'radish', 'turnip'],
    (_('BREAKFAST FOODS')): ['bacon', 'toast', 'waffle', 'pancake', 'egg', 'meal', 'bagel', 'cereal', 'fruit', 'hash'],
    (_('ANIMALS')): ['dog', 'cat', 'fish', 'horse', 'mouse', 'tiger', 'lion', 'bat', 'shark', 'sheep'],
    (_('VEHICLES')): ['truck', 'car', 'bus', 'train', 'plane', 'boat', 'bike', 'jeep', 'scooter', 'wagon'],
    (_('COLORS')): ['blue', 'grey', 'red', 'green', 'pink', 'white', 'brown', 'teal', 'black', 'beige'],
    (_('SPORTS')): ['ball', 'match', 'game', 'goal', 'swim', 'tennis', 'run', 'golf', 'coach', 'track'],
    (_('MUSIC GENRES')): ['jazz', 'blues', 'rock', 'pop', 'rap', 'folk', 'punk', 'dance', 'opera', 'metal'],
    (_('MOVIES')): ['movie', 'comedy', 'drama', 'horror', 'thrill', 'crime', 'action', 'family', 'scary', 'spy'],
    (_('BOOKS')): ['book', 'novel', 'story', 'essay', 'paper', 'author', 'poetry', 'title', 'genre', 'pages'],
    (_('CITIES')): ['city', 'town', 'metro', 'block', 'plaza', 'square', 'urban', 'park', 'village', 'court'],
    (_('MOUNTAINS')): ['hill', 'peak', 'rock', 'ridge', 'trail', 'stone', 'path', 'summit', 'cliff', 'crag'],
    (_('OCEANS')): ['sea', 'wave', 'beach', 'coast', 'tide', 'shore', 'water', 'island', 'reef', 'bay'],
    (_('WEATHER')): ['rain', 'wind', 'cloud', 'snow', 'storm', 'hail', 'fog', 'breeze', 'frost', 'chill'],
    (_('SPACE')): ['space', 'moon', 'star', 'comet', 'orbit', 'nova', 'planet', 'rocket', 'asteroid', 'ring'],
    (_('COMPUTERS')): ['laptop', 'coding', 'data', 'logic', 'files', 'mouse', 'click', 'input', 'server', 'error'],
    (_('SOCIAL MEDIA')): ['tweet', 'post', 'chat', 'likes', 'viral', 'trend', 'story', 'share', 'video', 'reels'],
    (_('FASHION')): ['style', 'pants', 'shirt', 'boots', 'dress', 'scarf', 'jeans', 'skirt', 'belt', 'glove'],
    (_('FOOD')): ['meal', 'snack', 'candy', 'pizza', 'bread', 'chips', 'fruit', 'toast', 'soup', 'nuts'],
    (_('TECHNOLOGY')): ['app', 'phone', 'robot', 'gadget', 'cloud', 'tablet', 'logic', 'server', 'screen', 'data'],
    (_('ECONOMICS')): ['money', 'trade', 'stock', 'price', 'market', 'value', 'profit', 'cost', 'tax', 'goods'],
    (_('POLITICS')): ['vote', 'party', 'court', 'policy', 'power', 'reform', 'bills', 'debate', 'leader', 'rights'],
    (_('HISTORY')): ['past', 'event', 'war', 'era', 'peace', 'reign', 'nation', 'empire', 'king', 'queen'],
    (_('HEALTH')): ['diet', 'fit', 'sleep', 'heal', 'virus', 'meds', 'doctor', 'pill', 'nurse', 'clinic'],
    (_('EDUCATION')): ['learn', 'study', 'grade', 'tests', 'books', 'essay', 'math', 'class', 'teach', 'notes'],
    (_('ART')): ['paint', 'craft', 'draw', 'color', 'shape', 'sketch', 'design', 'image', 'canvas', 'line'],
    (_('PHOTOGRAPHY')): ['photo', 'frame', 'lens', 'scene', 'focus', 'angle', 'light', 'flash', 'shot', 'view'],
    (_('ARCHITECTURE')): ['build', 'house', 'tower', 'brick', 'urban', 'plans', 'roof', 'rooms', 'stone', 'wall'],
    (_('NATURE')): ['plant', 'river', 'trees', 'grass', 'flora', 'field', 'woods', 'stone', 'bush', 'vine'],
    (_('CRAFTS')): ['sew', 'paint', 'knit', 'mold', 'lace', 'thread', 'bead', 'stitch', 'diy', 'craft'],
    (_('BOARD GAMES')): ['chess', 'dice', 'clue', 'cards', 'risk', 'pawn', 'check', 'move', 'jenga', 'board'],
    (_('VIDEO GAMES')): ['games', 'enemy', 'score', 'level', 'play', 'pixel', 'quest', 'shoot', 'jump', 'fight'],
    (_('GARDENING')): ['plant', 'grow', 'prune', 'tools', 'soil', 'water', 'seeds', 'weeds', 'herbs', 'pots'],
    (_('HOBBIES')): ['read', 'paint', 'dance', 'sew', 'knit', 'bake', 'craft', 'draw', 'play', 'write'],
    (_('DANCE')): ['ballet', 'tap', 'jazz', 'spin', 'twirl', 'moves', 'rhythm', 'break', 'step', 'tango'],
    (_('TRAVEL')): ['trip', 'hotel', 'map', 'roads', 'guide', 'train', 'plane', 'beach', 'visit', 'camp'],
    (_('FITNESS')): ['run', 'walk', 'yoga', 'cycle', 'bench', 'track', 'pullup', 'squat', 'pushup', 'fit'],
    (_('COOKING')): ['chef', 'cook', 'bake', 'grill', 'slice', 'stir', 'toast', 'boil', 'dough', 'steam'],
    (_('BEAUTY')): ['style', 'nails', 'skin', 'spa', 'hair', 'lip', 'face', 'gloss', 'cream', 'brush'],
    (_('MYTHOLOGY')): ['myth', 'god', 'beast', 'lore', 'hero', 'magic', 'curse', 'fate', 'oracle', 'troll'],
    (_('PHILOSOPHY')): ['logic', 'truth', 'mind', 'faith', 'value', 'moral', 'ideal', 'ideas', 'reason', 'thought'],
    (_('SCIENCE')): ['cells', 'atoms', 'study', 'light', 'tests', 'force', 'brain', 'field', 'virus', 'data'],
    (_('HOLIDAYS')): ['party', 'gifts', 'cards', 'feast', 'snow', 'elves', 'candy', 'tree', 'cheer', 'sled'],
    (_('FLOWERS')): ['rose', 'lily', 'daisy', 'tulip', 'bloom', 'petal', 'violet', 'poppy', 'orchid', 'bud'],
    (_('DRINKS')): ['water', 'juice', 'soda', 'shake', 'cider', 'tea', 'tonic', 'latte', 'mocha', 'milk'],
    (_('CLOTHING')): ['shirt', 'pants', 'dress', 'skirt', 'scarf', 'hat', 'vest', 'socks', 'boots', 'jeans'],
    (_('INSECTS')): ['bee', 'ant', 'moth', 'fly', 'gnat', 'roach', 'wasp', 'spider', 'beetle', 'tick'],
    (_('JOBS')): ['pilot', 'nurse', 'chef', 'clerk', 'actor', 'guard', 'miner', 'coach', 'agent', 'judge'],
    (_('TOOLS')): ['hammer', 'screw', 'blade', 'nails', 'drill', 'plier', 'saw', 'level', 'ruler', 'wrench'],
    (_('GAMES')): ['cards', 'dice', 'poker', 'clue', 'chess', 'risk', 'bingo', 'go', 'jenga', 'board'],
    (_('HOUSES')): ['home', 'cabin', 'loft', 'barn', 'tower', 'villa', 'castle', 'ranch', 'rooms', 'roof'],
    (_('DESERTS')): ['dunes', 'cactus', 'sands', 'rocks', 'dust', 'oasis', 'heat', 'dry', 'wind', 'sun'],
    (_('BIRDS')): ['crow', 'swan', 'robin', 'eagle', 'finch', 'crane', 'parrot', 'pigeon', 'sparrow', 'heron'],
    (_('BEACHES')): ['sand', 'reef', 'shore', 'coast', 'tide', 'waves', 'ocean', 'breeze', 'sun', 'shell'],
    (_('FURNITURE')): ['chair', 'table', 'sofa', 'bench', 'stool', 'desk', 'lamp', 'bed', 'shelf', 'couch'],
    (_('JEWELRY')): ['ring', 'brace', 'pearl', 'beads', 'stone', 'chain', 'gold', 'gem', 'watch', 'band'],
    (_('LANGUAGES')): ['latin', 'greek', 'hindi', 'hebrew', 'dutch', 'swahili', 'korean', 'arabic', 'french', 'spanish'],
    (_('PLANETS')): ['mars', 'venus', 'earth', 'pluto', 'orbit', 'ring', 'jupiter', 'saturn', 'neptune', 'moon'],
    (_('CAMPING')): ['tent', 'fire', 'trail', 'camp', 'lamp', 'gear', 'sleep', 'hike', 'tools', 'grill'],
    (_('MUSIC')): ['piano', 'lyric', 'vocal', 'drums', 'bass', 'guitar', 'notes', 'flute', 'violin', 'horn'],
    (_('WONDERS')): ['ruins', 'temple', 'tower', 'stone', 'castle', 'bridge', 'garden', 'pyramid', 'palace', 'statue'],
    (_('MYTHICAL CREATURES')): ['elf', 'fairy', 'hydra', 'troll', 'phoenix', 'dragon', 'sprite', 'beast', 'mermaid', 'giant'],
    (_('SHAPES')): ['circle', 'square', 'sphere', 'cone', 'cube', 'oval', 'hexagon', 'rhombus', 'prism', 'arc'],
    (_('DESSERTS')): ['cake', 'pie', 'cookie', 'tart', 'fudge', 'mousse', 'sorbet', 'gelato', 'pudding', 'donut'],
    (_('BEVERAGES')): ['coffee', 'mojito', 'squash', 'sprite', 'tonics', 'cocoa', 'smooth', 'latte', 'seltz', 'chai'],
    (_('HORROR')): ['ghost', 'haunt', 'spirit', 'scream', 'crypt', 'knife', 'curse', 'beast', 'zombie', 'creepy'],
    (_('ASTRONOMY')): ['nebula', 'cosmos', 'galaxy', 'comets', 'planet', 'lunar', 'space', 'stars', 'orbit', 'nova'],
    (_('FANTASY')): ['castle', 'dragon', 'wizard', 'magic', 'elves', 'troll', 'realm', 'sword', 'giants', 'knight'],
    (_('PIRATES')): ['parrot', 'swords', 'golden', 'rum', 'ships', 'shanty', 'cannon', 'mutiny', 'booty', 'pegleg'],
    (_('KITCHEN')): ['knife', 'spices', 'plates', 'spoons', 'mixers', 'aprons', 'utens', 'mixer', 'dishes', 'gloves'],
    (_('MONSTERS')): ['zombie', 'witch', 'ghoul', 'kraken', 'goblin', 'beast', 'hydra', 'slime', 'ghosts', 'fiends'],
    (_('GARDENS')): ['roses', 'weeds', 'hedges', 'herbs', 'shrubs', 'vines', 'seeds', 'blooms', 'roots', 'petals'],
    (_('TRAINS')): ['engine', 'tracks', 'cargos', 'ticket', 'rails', 'wagon', 'diesel', 'signal', 'horns', 'switch'],
    (_('LEGENDS')): ['heroes', 'mythos', 'quests', 'scroll', 'runes', 'giants', 'lore', 'epics', 'tales', 'swords'],
    (_('HIKING')): ['trails', 'climbs', 'packs', 'water', 'boots', 'rocks', 'views', 'camped', 'poles', 'steps'],
    (_('PLANTS')): ['fern', 'bamboo', 'ivy', 'shrub', 'bark', 'leaf', 'bud', 'stem', 'roots', 'moss'],
    (_('UNDERWATER LIFE')): ['fish', 'shrimp', 'coral', 'shark', 'whale', 'tuna', 'crab', 'squid', 'angler', 'urchin'],
    (_('WILDLIFE')): ['deer', 'fox', 'wolf', 'bear', 'owl', 'eagle', 'snake', 'frog', 'moose', 'otter'],
    (_('SEASONS')): ['summer', 'winter', 'autumn', 'spring', 'fall', 'season', 'harvest', 'snow', 'breeze', 'blossom'],
    (_('GEMS')): ['diamond', 'ruby', 'lapis', 'opal', 'jasper', 'emerald', 'topaz', 'garnet', 'pearl', 'onyx'],
    (_('EMOTIONS')): ['happy', 'sad', 'angry', 'excited', 'fear', 'love', 'joy', 'angst', 'grief', 'relief'],
    (_('CANDY')): ['sugar', 'fudge', 'candy', 'mint', 'gummy', 'sweet', 'treats', 'choco', 'caramel', 'nougat'],
    (_('TOOLS')): ['screw', 'drill', 'wrench', 'plier', 'knife', 'saw', 'level', 'ruler', 'blade', 'bolts'],
    (_('ALIENS')): ['alien', 'ufo', 'mars', 'green', 'ship', 'probe', 'beam', 'space', 'zoom', 'zap'],
    (_('CASTLES')): ['tower', 'moat', 'stone', 'arch', 'court', 'king', 'queen', 'walls', 'draw', 'gate'],
    (_('ISLANDS')): ['palm', 'sands', 'reef', 'coast', 'beach', 'sea', 'cove', 'boats', 'docks', 'tropic'],
    (_('CLOWNS')): ['clown', 'mime', 'wig', 'mask', 'red', 'nose', 'balloon', 'laugh', 'joke', 'prank'],
    (_('GHOSTS')): ['ghost', 'haunt', 'spook', 'ghoul', 'scare', 'crypt', 'eerie', 'fright', 'wail', 'chill'],
    (_('CAVES')): ['stone', 'bats', 'rocks', 'dark', 'stalag', 'depth', 'troll', 'echo', 'gloom', 'vault'],
    (_('ROBOTS')): ['servo', 'logic', 'cog', 'bolt', 'brain', 'cable', 'metal', 'tools', 'arm', 'gear'],
    (_('TREES')): ['oak', 'pine', 'bark', 'leaves', 'roots', 'twig', 'shade', 'apple', 'fruit', 'moss'],
    (_('WIZARDS')): ['magic', 'spell', 'cloak', 'staff', 'potion', 'witch', 'runes', 'charm', 'wand', 'books'],
    (_('VOLCANO')): ['lava', 'smoke', 'ash', 'crust', 'rock', 'fire', 'erupts', 'earth', 'crack', 'magma'],
    (_('DRAGONS')): ['scales', 'wings', 'fire', 'tail', 'claws', 'roar', 'flame', 'fangs', 'beast', 'lair'],
    (_('MIRRORS')): ['glass', 'frame', 'look', 'shine', 'image', 'reflect', 'ghost', 'room', 'angle', 'clean'],
    (_('FAIRIES')): ['pixie', 'tiny', 'wings', 'spark', 'magic', 'light', 'dust', 'charm', 'lore', 'elf'],
    (_('MARKETS')): ['trade', 'stalls', 'fruit', 'value', 'goods', 'crowd', 'money', 'sales', 'deals', 'price'],
    (_('TUNNELS')): ['earth', 'dark', 'shaft', 'mines', 'train', 'pipes', 'crawl', 'route', 'gates', 'dig']
}

