
related_words = {
    'Ice Cream Flavors': ['strawberry', 'cream', 'ice', 'vanilla', 'chocolate', 'dessert', 'sweet', 'cold', 'frozen', 'treat'],
    'Fruits': ['fruit', 'produce', 'citrus', 'apple', 'banana', 'peach', 'orange', 'cherry', 'grape', 'pear'],
    'Vegetables': ['vegetable', 'greens', 'carrot', 'lettuce', 'spinach', 'broccoli', 'pea', 'bean', 'cucumber', 'zucchini'],
    'Breakfast Foods': ['breakfast', 'meal', 'cereal', 'pancake', 'bacon', 'egg', 'toast', 'waffle', 'sausage', 'coffee'],
    'Animals': ['animal', 'mammal', 'bird', 'fish', 'reptile', 'amphibian', 'wildlife', 'dog', 'cat', 'elephant'],
    'Vehicles': ['car', 'truck', 'motorcycle', 'bus', 'train', 'plane', 'boat', 'bicycle', 'vehicle', 'transport'],
    'Colors': ['grey', 'red', 'blue', 'green', 'yellow', 'purple', 'black', 'white', 'orange', 'pink', 'brown'],
    'Sports': ['sport', 'game', 'football', 'basketball', 'baseball', 'soccer', 'tennis', 'golf', 'swimming', 'athletics'],
    'Music Genres': ['music', 'rock', 'pop', 'jazz', 'classical', 'hiphop', 'rap', 'country', 'electronic', 'blues'],
    'Movies': ['movie', 'film', 'cinema', 'comedy', 'drama', 'action', 'thriller', 'romance', 'horror', 'documentary'],
    'Books': ['book', 'novel', 'fiction', 'nonfiction', 'literature', 'author', 'reading', 'library', 'paperback', 'hardcover'],
    'Cities': ['city', 'town', 'village', 'metropolis', 'capital', 'suburb', 'downtown', 'skyscraper', 'street', 'neighborhood'],
    'Cities - Places' : ['Paris', 'Shanghai', 'Cairo', 'London', 'Washington', 'Toronto', 'Tokyo', 'Delhi', 'Moscow', 'Dubai'],
    'Mountains': ['mountain', 'hill', 'peak', 'summit', 'climb', 'alpine', 'hiking', 'rock', 'trail', 'ridge'],
    'Oceans': ['ocean', 'sea', 'wave', 'beach', 'shore', 'coast', 'marine', 'coral', 'island', 'underwater'],
    'Weather': ['weather', 'sun', 'rain', 'cloud', 'snow', 'storm', 'wind', 'temperature', 'humidity', 'forecast'],
    'Space': ['space', 'planet', 'star', 'galaxy', 'universe', 'moon', 'astronaut', 'satellite', 'comet', 'blackhole'],
    'Computers': ['computer', 'laptop', 'software', 'hardware', 'programming', 'internet', 'network', 'coding', 'technology', 'data'],
    'Social Media': ['social media', 'platform', 'post', 'tweet', 'like', 'follow', 'share', 'Instagram', 'Facebook', 'Snapchat'],
    'Fashion': ['fashion', 'clothing', 'style', 'design', 'outfit', 'trend', 'designer', 'runway', 'couture', 'accessories'],
    'Food': ['breakfast', 'meal', 'dinner', 'lunch', 'snack', 'delicious', 'cuisine', 'dish', 'restaurant', 'tasty'],
    'Technology': ['technology', 'innovation', 'device', 'smartphone', 'gadget', 'computer', 'robot', 'internet', 'app', 'virtual'],
    'Economics': ['economy', 'market', 'money', 'trade', 'business', 'finance', 'currency', 'stock', 'investment', 'growth'],
    'Politics': ['politics', 'government', 'election', 'candidate', 'vote', 'policy', 'congress', 'debate', 'party', 'president'],
    'History': ['history', 'past', 'event', 'civilization', 'empire', 'war', 'king', 'queen', 'revolution', 'ancient'],
    'Health': ['health', 'wellness', 'fitness', 'nutrition', 'exercise', 'doctor', 'hospital', 'medicine', 'therapy', 'mentalhealth'],
    'Education': ['education', 'learning', 'school', 'teacher', 'student', 'college', 'university', 'degree', 'study', 'knowledge'],
    'Art': ['art', 'painting', 'sculpture', 'gallery', 'museum', 'artist', 'drawing', 'exhibit', 'creativity', 'abstract'],
    'Photography': ['photography', 'camera', 'lens', 'portrait', 'landscape', 'photo', 'shot', 'image', 'picture', 'focus'],
    'Architecture': ['architecture', 'building', 'design', 'construction', 'urban', 'skyscraper', 'bridge', 'house', 'office', 'cityscape'],
    'Nature': ['nature', 'forest', 'tree', 'wildlife', 'river', 'lake', 'desert', 'mountain', 'ocean', 'park'],
    'Crafts': ['craft', 'DIY', 'artisanal', 'handmade', 'sewing', 'knitting', 'painting', 'sculpting', 'beading', 'pottery'],
    'Board Games': ['boardgame', 'game', 'chess', 'checkers', 'puzzle', 'strategy', 'play', 'pieces', 'dice', 'board'],
    'Video Games': ['videogame', 'gaming', 'console', 'PC', 'controller', 'action', 'adventure', 'RPG', 'shooter', 'multiplayer'],
    'Gardening': ['gardening', 'plants', 'flowers', 'green', 'soil', 'compost', 'seed', 'flowerbed', 'landscaping', 'botanist'],
    'Hobbies': ['hobby', 'interest', 'crafting', 'sports', 'reading', 'collecting', 'writing', 'photography', 'gaming', 'knitting'],
    'Dance': ['dance', 'ballet', 'hip-hop', 'jazz', 'tap', 'salsa', 'ballroom', 'choreography', 'perform', 'rhythm'],
    'Travel': ['travel', 'tourism', 'vacation', 'destination', 'trip', 'journey', 'hotel', 'adventure', 'explore', 'backpacking'],
    'Fitness': ['fitness', 'exercise', 'strength', 'gym', 'workout', 'health', 'endurance', 'bodybuilding', 'yoga', 'cardio'],
    'Cooking': ['cooking', 'recipe', 'chef', 'kitchen', 'bake', 'grill', 'fry', 'saute', 'dish', 'ingredient'],
    'Beauty': ['beauty', 'makeup', 'skin', 'cosmetics', 'hair', 'fashion', 'spa', 'perfume', 'lotion', 'skincare'],
    'Technology Trends': ['technology', 'apple', 'blockchain', 'algorithm', 'linux', 'innovation', 'gadgets', 'tech', 'automation', 'future'],
    'Mythology': ['mythology', 'god', 'goddess', 'myth', 'legend', 'creature', 'pantheon', 'Greek', 'Norse', 'Egyptian'],
    'Philosophy': ['philosophy', 'thought', 'ethics', 'logic', 'reasoning', 'wisdom', 'morality', 'theory', 'physics', 'epistemology'],
    'Animals - Wild': ['wild animal', 'predator', 'prey', 'jungle', 'safari', 'tiger', 'lion', 'bear', 'elephant', 'zebra'],
    'Animals - Pets': ['pet', 'dog', 'cat', 'fish', 'rabbit', 'hamster', 'bird', 'animal', 'companion', 'pup'],
    'Space Exploration': ['exploration', 'NASA', 'astronaut', 'mission', 'rocket', 'spacecraft', 'planetary', 'research', 'cosmos', 'voyager'],
    'Marketing': ['marketing', 'advertising', 'brand', 'campaign', 'consumer', 'strategy', 'promotion', 'SEO', 'content', 'social media'],
    'Personal Finance': ['finance', 'saving', 'budget', 'debt', 'investing', 'taxes', 'bank', 'credit', 'retirement', 'stocks'],
    'Parenting': ['parenting', 'family', 'children', 'kids', 'school', 'discipline', 'advice', 'education', 'mom', 'dad'],
    'Science': ['science', 'experiment', 'research', 'biology', 'chemistry', 'physics', 'astronomy', 'geology', 'scientist', 'theory'],
    'Crime': ['crime', 'criminal', 'police', 'investigation', 'detective', 'case', 'suspect', 'murder', 'robbery', 'theft'],
    'Luxury': ['luxury', 'wealth', 'expensive', 'exclusive', 'highend', 'designer', 'opulent', 'premium', 'elite', 'prestige'],
    'Holiday Traditions': ['holiday', 'Christmas', 'Thanksgiving', 'Hanukkah', 'Easter', 'newyear', 'tradition', 'celebration', 'festivity', 'family'],
    'Craft Beer': ['craftbeer', 'brewery', 'IPA', 'lager', 'ale', 'stout', 'paleale', 'tasting', 'hops', 'brewing'],
    'Wine': ['wine', 'redwine', 'whitewine', 'vineyard', 'grapes', 'winery', 'sommelier', 'tasting', 'vintage', 'alcohol'],
    'Cultural Festivals': ['festival', 'celebration', 'music', 'dance', 'food', 'tradition', 'ceremony', 'culture', 'art', 'parade'],
    'Street Art': ['streetart', 'graffiti', 'urban', 'spraypaint', 'mural', 'artist', 'painting', 'public', 'expression', 'creative'],
    'Technology Gadgets': ['gadget', 'smartphone', 'tablet', 'watch', 'camera', 'headphones', 'speaker', 'device', 'VR', 'Bluetooth'],
}

