related_words = {
    'ICE CREAM FLAVORS': ['berry', 'cream', 'ice', 'vanilla', 'choco', 'sweet', 'cold', 'treat', 'scoop', 'cone'],
    'FRUITS': ['fruit', 'apple', 'banana', 'peach', 'grape', 'citrus', 'plum', 'melon', 'mango', 'kiwi'],
    'VEGETABLES': ['greens', 'carrot', 'beans', 'pea', 'beet', 'onion', 'cabbage', 'squash', 'radish', 'turnip'],
    'BREAKFAST FOODS': ['bacon', 'toast', 'waffle', 'pancake', 'egg', 'meal', 'bagel', 'cereal', 'fruit', 'hash'],
    'ANIMALS': ['dog', 'cat', 'fish', 'horse', 'mouse', 'tiger', 'lion', 'bat', 'shark', 'sheep'],
    'VEHICLES': ['truck', 'car', 'bus', 'train', 'plane', 'boat', 'bike', 'jeep', 'scooter', 'wagon'],
    'COLORS': ['blue', 'grey', 'red', 'green', 'pink', 'white', 'brown', 'teal', 'black', 'beige'],
    'SPORTS': ['ball', 'match', 'game', 'goal', 'swim', 'tennis', 'run', 'golf', 'coach', 'track'],
    'MUSIC GENRES': ['jazz', 'blues', 'rock', 'pop', 'rap', 'folk', 'punk', 'dance', 'opera', 'metal'],
    'MOVIES': ['movie', 'comedy', 'drama', 'horror', 'thrill', 'crime', 'action', 'family', 'scary', 'spy'],
    'BOOKS': ['book', 'novel', 'story', 'essay', 'paper', 'author', 'poetry', 'title', 'genre', 'pages'],
    'CITIES': ['city', 'town', 'metro', 'block', 'plaza', 'square', 'urban', 'park', 'village', 'court'],
    'MOUNTAINS': ['hill', 'peak', 'rock', 'ridge', 'trail', 'stone', 'path', 'summit', 'cliff', 'crag'],
    'OCEANS': ['sea', 'wave', 'beach', 'coast', 'tide', 'shore', 'water', 'island', 'reef', 'bay'],
    'WEATHER': ['rain', 'wind', 'cloud', 'snow', 'storm', 'hail', 'fog', 'breeze', 'frost', 'chill'],
    'SPACE': ['space', 'moon', 'star', 'comet', 'orbit', 'nova', 'planet', 'rocket', 'asteroid', 'ring'],
    'COMPUTERS': ['laptop', 'coding', 'data', 'logic', 'files', 'mouse', 'click', 'input', 'server', 'error'],
    'SOCIAL MEDIA': ['tweet', 'post', 'chat', 'likes', 'viral', 'trend', 'story', 'share', 'video', 'reels'],
    'FASHION': ['style', 'pants', 'shirt', 'boots', 'dress', 'scarf', 'jeans', 'skirt', 'belt', 'glove'],
    'FOOD': ['meal', 'snack', 'candy', 'pizza', 'bread', 'chips', 'fruit', 'toast', 'soup', 'nuts'],
    'TECHNOLOGY': ['app', 'phone', 'robot', 'gadget', 'cloud', 'tablet', 'logic', 'server', 'screen', 'data'],
    'ECONOMICS': ['money', 'trade', 'stock', 'price', 'market', 'value', 'profit', 'cost', 'tax', 'goods'],
    'POLITICS': ['vote', 'party', 'court', 'policy', 'power', 'reform', 'bills', 'debate', 'leader', 'rights'],
    'HISTORY': ['past', 'event', 'war', 'era', 'peace', 'reign', 'nation', 'empire', 'king', 'queen'],
    'HEALTH': ['diet', 'fit', 'sleep', 'heal', 'virus', 'meds', 'doctor', 'pill', 'nurse', 'clinic'],
    'EDUCATION': ['learn', 'study', 'grade', 'tests', 'books', 'essay', 'math', 'class', 'teach', 'notes'],
    'ART': ['paint', 'craft', 'draw', 'color', 'shape', 'sketch', 'design', 'image', 'canvas', 'line'],
    'PHOTOGRAPHY': ['photo', 'frame', 'lens', 'scene', 'focus', 'angle', 'light', 'flash', 'shot', 'view'],
    'ARCHITECTURE': ['build', 'house', 'tower', 'brick', 'urban', 'plans', 'roof', 'rooms', 'stone', 'wall'],
    'NATURE': ['plant', 'river', 'trees', 'grass', 'flora', 'field', 'woods', 'stone', 'bush', 'vine'],
    'CRAFTS': ['sew', 'paint', 'knit', 'mold', 'lace', 'thread', 'bead', 'stitch', 'DIY', 'craft'],
    'BOARD GAMES': ['chess', 'dice', 'clue', 'cards', 'risk', 'pawn', 'check', 'move', 'jenga', 'board'],
    'VIDEO GAMES': ['games', 'enemy', 'score', 'level', 'play', 'pixel', 'quest', 'shoot', 'jump', 'fight'],
    'GARDENING': ['plant', 'grow', 'prune', 'tools', 'soil', 'water', 'seeds', 'weeds', 'herbs', 'pots'],
    'HOBBIES': ['read', 'paint', 'dance', 'sew', 'knit', 'bake', 'craft', 'draw', 'play', 'write'],
    'DANCE': ['ballet', 'tap', 'jazz', 'spin', 'twirl', 'moves', 'rhythm', 'break', 'step', 'tango'],
    'TRAVEL': ['trip', 'hotel', 'map', 'roads', 'guide', 'train', 'plane', 'beach', 'visit', 'camp'],
    'FITNESS': ['run', 'walk', 'yoga', 'cycle', 'bench', 'track', 'pullup', 'squat', 'pushup', 'fit'],
    'COOKING': ['chef', 'cook', 'bake', 'grill', 'slice', 'stir', 'toast', 'boil', 'dough', 'steam'],
    'BEAUTY': ['style', 'nails', 'skin', 'spa', 'hair', 'lip', 'face', 'gloss', 'cream', 'brush'],
    'MYTHOLOGY': ['myth', 'god', 'beast', 'lore', 'hero', 'magic', 'curse', 'fate', 'oracle', 'troll'],
    'PHILOSOPHY': ['logic', 'truth', 'mind', 'faith', 'value', 'moral', 'ideal', 'ideas', 'reason', 'thought'],
    'SCIENCE': ['cells', 'atoms', 'study', 'light', 'tests', 'force', 'brain', 'field', 'virus', 'data'],
    'HOLIDAYS': ['party', 'gifts', 'cards', 'feast', 'snow', 'elves', 'candy', 'tree', 'cheer', 'sled'],
    'FLOWERS': ['rose', 'lily', 'daisy', 'tulip', 'bloom', 'petal', 'violet', 'poppy', 'orchid', 'bud'],
    'DRINKS': ['water', 'juice', 'soda', 'shake', 'cider', 'tea', 'tonic', 'latte', 'mocha', 'milk'],
    'CLOTHING': ['shirt', 'pants', 'dress', 'skirt', 'scarf', 'hat', 'vest', 'socks', 'boots', 'jeans'],
    'INSECTS': ['bee', 'ant', 'moth', 'fly', 'gnat', 'roach', 'wasp', 'spider', 'beetle', 'tick'],
    'JOBS': ['pilot', 'nurse', 'chef', 'clerk', 'actor', 'guard', 'miner', 'coach', 'agent', 'judge'],
    'TOOLS': ['hammer', 'screw', 'blade', 'nails', 'drill', 'plier', 'saw', 'level', 'ruler', 'wrench'],
    'GAMES': ['cards', 'dice', 'poker', 'clue', 'chess', 'risk', 'bingo', 'go', 'jenga', 'board'],
    'HOUSES': ['home', 'cabin', 'loft', 'barn', 'tower', 'villa', 'castle', 'ranch', 'rooms', 'roof'],
    'DESERTS': ['dunes', 'cactus', 'sands', 'rocks', 'dust', 'oasis', 'heat', 'dry', 'wind', 'sun'],
    'BIRDS': ['crow', 'swan', 'robin', 'eagle', 'finch', 'crane', 'parrot', 'pigeon', 'sparrow', 'heron'],
    'BEACHES': ['sand', 'reef', 'shore', 'coast', 'tide', 'waves', 'ocean', 'breeze', 'sun', 'shell'],
    'FURNITURE': ['chair', 'table', 'sofa', 'bench', 'stool', 'desk', 'lamp', 'bed', 'shelf', 'couch'],
    'JEWELRY': ['ring', 'brace', 'pearl', 'beads', 'stone', 'chain', 'gold', 'gem', 'watch', 'band'],
    'LANGUAGES': ['latin', 'greek', 'hindi', 'hebrew', 'dutch', 'swahili', 'korean', 'arabic', 'french', 'spanish'],
    'PLANETS': ['mars', 'venus', 'earth', 'pluto', 'orbit', 'ring', 'jupiter', 'saturn', 'neptune', 'moon'],
    'CAMPING': ['tent', 'fire', 'trail', 'camp', 'lamp', 'gear', 'sleep', 'hike', 'tools', 'grill'],
    'MUSIC': ['piano', 'lyric', 'vocal', 'drums', 'bass', 'guitar', 'notes', 'flute', 'violin', 'horn'],
    'WONDERS': ['ruins', 'temple', 'tower', 'stone', 'castle', 'bridge', 'garden', 'pyramid', 'palace', 'statue'],
    'MYTHICAL CREATURES': ['elf', 'fairy', 'hydra', 'troll', 'phoenix', 'dragon', 'sprite', 'beast', 'mermaid', 'giant'],
    'SHAPES': ['circle', 'square', 'sphere', 'cone', 'cube', 'oval', 'hexagon', 'rhombus', 'prism', 'arc'],
    'DESSERTS': ['cake', 'pie', 'cookie', 'tart', 'fudge', 'mousse', 'sorbet', 'gelato', 'pudding', 'donut'],
    'BEVERAGES': ['coffee', 'mojito', 'squash', 'sprite', 'tonics', 'cocoa', 'smooth', 'latte', 'seltz', 'chai'],
    'HORROR': ['ghost', 'haunt', 'spirit', 'scream', 'crypt', 'knife', 'curse', 'beast', 'zombie', 'creepy'],
    'ASTRONOMY': ['nebula', 'cosmos', 'galaxy', 'comets', 'planet', 'lunar', 'space', 'stars', 'orbit', 'nova'],
    'FANTASY': ['castle', 'dragon', 'wizard', 'magic', 'elves', 'troll', 'realm', 'sword', 'giants', 'knight'],
    'PIRATES': ['parrot', 'swords', 'golden', 'rum', 'ships', 'shanty', 'cannon', 'mutiny', 'booty', 'pegleg'],
    'KITCHEN': ['knife', 'spices', 'plates', 'spoons', 'mixers', 'aprons', 'utens', 'mixer', 'dishes', 'gloves'],
    'MONSTERS': ['zombie', 'witch', 'ghoul', 'kraken', 'goblin', 'beast', 'hydra', 'slime', 'ghosts', 'fiends'],
    'GARDENS': ['roses', 'weeds', 'hedges', 'herbs', 'shrubs', 'vines', 'seeds', 'blooms', 'roots', 'petals'],
    'TRAINS': ['engine', 'tracks', 'cargos', 'ticket', 'rails', 'wagon', 'diesel', 'signal', 'horns', 'switch'],
    'LEGENDS': ['heroes', 'mythos', 'quests', 'scroll', 'runes', 'giants', 'lore', 'epics', 'tales', 'swords'],
    'HIKING': ['trails', 'climbs', 'packs', 'water', 'boots', 'rocks', 'views', 'camped', 'poles', 'steps'],
    'PLANTS': ['fern', 'bamboo', 'ivy', 'shrub', 'bark', 'leaf', 'bud', 'stem', 'roots', 'moss'],
    'UNDERWATER LIFE': ['fish', 'shrimp', 'coral', 'shark', 'whale', 'tuna', 'crab', 'squid', 'angler', 'urchin'],
    'WILDLIFE': ['deer', 'fox', 'wolf', 'bear', 'owl', 'eagle', 'snake', 'frog', 'moose', 'otter'],
    'SEASONS': ['summer', 'winter', 'autumn', 'spring', 'fall', 'season', 'harvest', 'snow', 'breeze', 'blossom'],
    'GEMS': ['diamond', 'ruby', 'lapis', 'opal', 'jasper', 'emerald', 'topaz', 'garnet', 'pearl', 'onyx'],
    'EMOTIONS': ['happy', 'sad', 'angry', 'excited', 'fear', 'love', 'joy', 'angst', 'grief', 'relief']
}

